### PR TITLE
feat(map): Add map page

### PR DESCRIPTION
**Pull request by ikanexus**
https://map.pestoverse-ikanexus.pages.dev/map

### CODE REVIEW

**Comment by ikanexus** [comment]
interestingly I just noticed the marker image has disappeared when deployed

**Comment by Tougrel** [comment]
I was thinking of using a different layout on the map page. Having a full-screen map with fixed positioned elements on top of it 🤔 What do you think?

**Comment by ikanexus** [comment]
yeah I was thinking about the same thing actually, probably just needs some tweaks to the nav css so that it floats 🤞🏻 as the map is already 100%/100%

**Comment by Tougrel** [comment]
I was thinking of removing the theme button overall (or maybe remove the text and leave the icon only) from the UI in the map page 🤔 We can also try using the `layouts` directory if we are going for different layouts on pages 👍

**Comment by ikanexus** [comment]
image

**Comment by Tougrel** [comment]
I think we should consider adding maximum boundaries on the map cause it duplicates when you scroll horizontally and the markers don't follow.

**Review by Tougrel — APPROVED** [review]

**Pull request merged**
